### ISSUE TITLE
search highlight, visual mode etc. are indistinguishable

### ISSUE THREAD

**Issue by zekzekus** [thenewvu/vim-colors-blueprint#2]
I love this color scheme but have one problem. It does not show any highlights for InsSearch, Search and Visual highlight groups. 

One common thing of these group, all of them gui property is set to standout. I checked vim docs but no extra info on standout. 

I don't think this is an intentional behaviour. 

Thanks for great work.

**Comment by zekzekus** [comment]
Just realized that this problem exists on Neovim. Not vanilla Vim. Both are built from HEAD.

**Comment by thenewvu** [comment]
Thanks for reporting the issue.

Color schemes usually are opinionated and were not intent to work for everyone. So I think it's better to clone and modify it by yourself. I believe the syntax is pretty easy, the license is free as beer.

In case you don't know how to do it yet, you just need to make a copy of [colors/blueprint.vim](https://github.com/thenewvu/vim-colors-blueprint/blob/master/colors/blueprint.vim) to `~/.config/nvim/colors/blueprint.vim` with Neovim ( or `~/.vim/colors/blueprint.vim` with Vim), remove installing the scheme from your .vimrc if necessary, then modify the copy as your need.
